# Generated by Django 5.0.6 on 2024-05-23 06:45

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.webp', force_format='JPEG', keep_meta=False, quality=95, scale=0.5, size=[1080, 1080], upload_to='customer_images/'),
        ),
    ]
